# Generated by Django 4.2.1 on 2023-05-19 19:48

import base.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='helo', max_length=100)),
                ('duration', models.DurationField(default=None)),
                ('upload_file', models.FileField(blank=True, upload_to=base.models.upload_path)),
                ('uploaded_on', models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 48, 10, 940928, tzinfo=datetime.timezone.utc))),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=256)),
                ('timestamp', models.DurationField()),
                ('added_on', models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 48, 10, 940928, tzinfo=datetime.timezone.utc))),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='base.audio')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DurationField()),
                ('liked_on', models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 48, 10, 940928, tzinfo=datetime.timezone.utc))),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='base.comment')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
