# Generated by Django 4.2.1 on 2023-05-19 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='audio',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 49, 59, 457023, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 49, 59, 457023, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 49, 59, 457023, tzinfo=datetime.timezone.utc)),
        ),
    ]
